import { z } from "zod";


export const currentWeatherSchema = z.object({
  is_day: z.number(),
  temperature: z.number(),
  time: z.number(),
  weathercode: z.number(),
  winddirection: z.number(),
  windspeed: z.number(),
});
 
export const dailySchema = z.object({
  apparent_temperature_max: z.array(z.number()),
  apparent_temperature_min: z.array(z.number()),
  sunrise: z.array(z.number()),
  sunset: z.array(z.number()),
  temperature_2m_max: z.array(z.number()),
  temperature_2m_min: z.array(z.number()),
  time: z.array(z.number()),
  uv_index_clear_sky_max: z.array(z.number()),
  uv_index_max: z.array(z.number()),
  weathercode: z.array(z.number()),
});
 
export const dailyUnitsSchema = z.object({
  apparent_temperature_max: z.string(),
  apparent_temperature_min: z.string(),
  sunrise: z.string(),
  sunset: z.string(),
  temperature_2m_max: z.string(),
  temperature_2m_min: z.string(),
  time: z.string(),
  uv_index_clear_sky_max: z.string(),
  uv_index_max: z.string(),
  weathercode: z.string(),
});
 
export const hourlySchema = z.object({
  apparent_temperature: z.array(z.number()),
  dewpoint_2m: z.array(z.number()),
  is_day: z.array(z.number()),
  precipitation: z.array(z.number()),
  precipitation_probability: z.array(z.number()),
  rain: z.array(z.number()),
  relativehumidity_2m: z.array(z.number()),
  showers: z.array(z.number()),
  snow_depth: z.array(z.number()),
  snowfall: z.array(z.number()),
  temperature_2m: z.array(z.number()),
  time: z.array(z.number()),
  uv_index: z.array(z.number()),
  uv_index_clear_sky: z.array(z.number()),
});
 
export const hourlyUnitsSchema = z.object({
  apparent_temperature: z.string(),
  dewpoint_2m: z.string(),
  is_day: z.string(),
  precipitation: z.string(),
  precipitation_probability: z.string(),
  rain: z.string(),
  relativehumidity_2m: z.string(),
  showers: z.string(),
  snow_depth: z.string(),
  snowfall: z.string(),
  temperature_2m: z.string(),
  time: z.string(),
  uv_index: z.string(),
  uv_index_clear_sky: z.string(),
});
 
export const weatherDataSchema = z.object({
  current_weather: currentWeatherSchema,
  daily: dailySchema,
  daily_units: dailyUnitsSchema,
  elevation: z.number(),
  generationtime_ms: z.number(),
  hourly: hourlySchema,
  hourly_units: hourlyUnitsSchema,
  latitude: z.number(),
  longitude: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  utc_offset_seconds: z.number(),
});
 
export type WeatherData = z.infer<typeof weatherDataSchema>;
 
export const openMeteoCurrentSchema = z.object({
  time: z.string(),
  temperature_2m: z.number(),
  relative_humidity_2m: z.number(),
  apparent_temperature: z.number(),
  is_day: z.number(),
  precipitation: z.number(),
  rain: z.number(),
  showers: z.number(),
  snowfall: z.number(),
  weather_code: z.number(),
  cloud_cover: z.number(),
  pressure_msl: z.number(),
  surface_pressure: z.number(),
  wind_speed_10m: z.number(),
  wind_direction_10m: z.number(),
  wind_gusts_10m: z.number(),
});
 
export const openMeteoResponseSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  elevation: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  utc_offset_seconds: z.number(),
  generationtime_ms: z.number(),
  current: openMeteoCurrentSchema,
  current_units: z.object({
    time: z.string(),
    temperature_2m: z.string(),
    relative_humidity_2m: z.string(),
    apparent_temperature: z.string(),
    is_day: z.string(),
    precipitation: z.string(),
    rain: z.string(),
    showers: z.string(),
    snowfall: z.string(),
    weather_code: z.string(),
    cloud_cover: z.string(),
    pressure_msl: z.string(),
    surface_pressure: z.string(),
    wind_speed_10m: z.string(),
    wind_direction_10m: z.string(),
    wind_gusts_10m: z.string(),
  }),
  hourly: z.object({
    time: z.array(z.string()),
    temperature_2m: z.array(z.number()),
    relative_humidity_2m: z.array(z.number()),
    dewpoint_2m: z.array(z.number()),
    apparent_temperature: z.array(z.number()),
    precipitation_probability: z.array(z.number()),
    precipitation: z.array(z.number()),
    rain: z.array(z.number()),
    showers: z.array(z.number()),
    snowfall: z.array(z.number()),
    snow_depth: z.array(z.number()),
    weather_code: z.array(z.number()),
    pressure_msl: z.array(z.number()),
    surface_pressure: z.array(z.number()),
    cloud_cover: z.array(z.number()),
    visibility: z.array(z.number()),
    evapotranspiration: z.array(z.number()),
    et0_fao_evapotranspiration: z.array(z.number()),
    vapour_pressure_deficit: z.array(z.number()),
    wind_speed_10m: z.array(z.number()),
    wind_speed_80m: z.array(z.number()),
    wind_speed_120m: z.array(z.number()),
    wind_speed_180m: z.array(z.number()),
    wind_direction_10m: z.array(z.number()),
    wind_direction_80m: z.array(z.number()),
    wind_direction_120m: z.array(z.number()),
    wind_direction_180m: z.array(z.number()),
    wind_gusts_10m: z.array(z.number()),
    temperature_80m: z.array(z.number()),
    temperature_120m: z.array(z.number()),
    temperature_180m: z.array(z.number()),
    soil_temperature_0cm: z.array(z.number()),
    soil_temperature_6cm: z.array(z.number()),
    soil_temperature_18cm: z.array(z.number()),
    soil_temperature_54cm: z.array(z.number()),
    soil_moisture_0_to_1cm: z.array(z.number()),
    soil_moisture_1_to_3cm: z.array(z.number()),
    soil_moisture_3_to_9cm: z.array(z.number()),
    soil_moisture_9_to_27cm: z.array(z.number()),
    soil_moisture_27_to_81cm: z.array(z.number()),
    is_day: z.array(z.number()),
    uv_index: z.array(z.number()),
    uv_index_clear_sky: z.array(z.number()),
  }),
  hourly_units: z.object({
    time: z.string(),
    temperature_2m: z.string(),
    relative_humidity_2m: z.string(),
    dewpoint_2m: z.string(),
    apparent_temperature: z.string(),
    precipitation_probability: z.string(),
    precipitation: z.string(),
    rain: z.string(),
    showers: z.string(),
    snowfall: z.string(),
    snow_depth: z.string(),
    weather_code: z.string(),
    pressure_msl: z.string(),
    surface_pressure: z.string(),
    cloud_cover: z.string(),
    visibility: z.string(),
    evapotranspiration: z.string(),
    et0_fao_evapotranspiration: z.string(),
    vapour_pressure_deficit: z.string(),
    wind_speed_10m: z.string(),
    wind_speed_80m: z.string(),
    wind_speed_120m: z.string(),
    wind_speed_180m: z.string(),
    wind_direction_10m: z.string(),
    wind_direction_80m: z.string(),
    wind_direction_120m: z.string(),
    wind_direction_180m: z.string(),
    wind_gusts_10m: z.string(),
    temperature_80m: z.string(),
    temperature_120m: z.string(),
    temperature_180m: z.string(),
    soil_temperature_0cm: z.string(),
    soil_temperature_6cm: z.string(),
    soil_temperature_18cm: z.string(),
    soil_temperature_54cm: z.string(),
    soil_moisture_0_to_1cm: z.string(),
    soil_moisture_1_to_3cm: z.string(),
    soil_moisture_3_to_9cm: z.string(),
    soil_moisture_9_to_27cm: z.string(),
    soil_moisture_27_to_81cm: z.string(),
    is_day: z.string(),
    uv_index: z.string(),
    uv_index_clear_sky: z.string(),
  }),
  daily: z.object({
    time: z.array(z.string()),
    weather_code: z.array(z.number()),
    temperature_2m_max: z.array(z.number()),
    temperature_2m_min: z.array(z.number()),
    apparent_temperature_max: z.array(z.number()),
    apparent_temperature_min: z.array(z.number()),
    sunrise: z.array(z.string()),
    sunset: z.array(z.string()),
    daylight_duration: z.array(z.number()),
    sunshine_duration: z.array(z.number()),
    uv_index_max: z.array(z.number()),
    uv_index_clear_sky_max: z.array(z.number()),
    precipitation_sum: z.array(z.number()),
    rain_sum: z.array(z.number()),
    showers_sum: z.array(z.number()),
    snowfall_sum: z.array(z.number()),
    precipitation_hours: z.array(z.number()),
    precipitation_probability_max: z.array(z.number()),
    wind_speed_10m_max: z.array(z.number()),
    wind_gusts_10m_max: z.array(z.number()),
    wind_direction_10m_dominant: z.array(z.number()),
    shortwave_radiation_sum: z.array(z.number()),
    et0_fao_evapotranspiration: z.array(z.number()),
  }),
  daily_units: z.object({
    time: z.string(),
    weather_code: z.string(),
    temperature_2m_max: z.string(),
    temperature_2m_min: z.string(),
    apparent_temperature_max: z.string(),
    apparent_temperature_min: z.string(),
    sunrise: z.string(),
    sunset: z.string(),
    daylight_duration: z.string(),
    sunshine_duration: z.string(),
    uv_index_max: z.string(),
    uv_index_clear_sky_max: z.string(),
    precipitation_sum: z.string(),
    rain_sum: z.string(),
    showers_sum: z.string(),
    snowfall_sum: z.string(),
    precipitation_hours: z.string(),
    precipitation_probability_max: z.string(),
    wind_speed_10m_max: z.string(),
    wind_gusts_10m_max: z.string(),
    wind_direction_10m_dominant: z.string(),
    shortwave_radiation_sum: z.string(),
    et0_fao_evapotranspiration: z.string(),
  }),
});
 
export type OpenMeteoResponse = z.infer<typeof openMeteoResponseSchema>;
